global using TimeTracker.API.Repositories;
global using TimeTracker.Shared.Models.TimeEntry;
global using TimeTracker.Shared.Entities;
global using TimeTracker.API.Services;
global using TimeTracker.API.Data;
global using TimeTracker.Shared.Exceptions;
global using Microsoft.EntityFrameworkCore;
global using TimeTracker.Shared.Models.Project;
global using Mapster;
